"use strict";
(() => {
const svg=document.querySelector('#abTree'); if(!svg) return;
const EXAMPLES={
  one:{name:'Example 1',viewBox:'0 0 1120 610',nodes:{R:{x:560,y:55,t:'MAX',kids:['A','D','H']},A:{x:230,y:180,t:'MIN',kids:['B','C']},D:{x:560,y:180,t:'MIN',kids:['E','F','G']},H:{x:900,y:180,t:'MIN',kids:['I','J']},B:{x:150,y:325,t:'MAX',kids:['l4','l3']},C:{x:310,y:325,t:'MAX',kids:['l6','l2a']},E:{x:475,y:325,t:'MAX',kids:['l2b','l1a']},F:{x:610,y:325,t:'MAX',kids:['l9','l5a']},G:{x:745,y:325,t:'MAX',kids:['l3b','l1b']},I:{x:865,y:325,t:'MAX',kids:['l5b','l4b']},J:{x:1010,y:325,t:'MAX',kids:['l7','l5c']}},leaves:{l4:{x:120,y:500,v:4},l3:{x:180,y:500,v:3},l6:{x:280,y:500,v:6},l2a:{x:340,y:500,v:2},l2b:{x:445,y:500,v:2},l1a:{x:505,y:500,v:1},l9:{x:580,y:500,v:9},l5a:{x:640,y:500,v:5},l3b:{x:715,y:500,v:3},l1b:{x:775,y:500,v:1},l5b:{x:835,y:500,v:5},l4b:{x:895,y:500,v:4},l7:{x:980,y:500,v:7},l5c:{x:1040,y:500,v:5}}},
  two:{name:'Example 2',viewBox:'0 0 1120 610',nodes:{R:{x:560,y:48,t:'MAX',kids:['A','D','H']},A:{x:265,y:165,t:'MIN',kids:['B','l2x','C']},D:{x:560,y:165,t:'MIN',kids:['l3x','F','l1x']},H:{x:880,y:165,t:'MIN',kids:['I','J']},B:{x:120,y:315,t:'MAX',kids:['l0a','l2a','l1a']},C:{x:350,y:315,t:'MAX',kids:['l4','l3a']},F:{x:560,y:315,t:'MAX',kids:['l1b','l0b']},I:{x:810,y:315,t:'MAX',kids:['l3b','l2b','l3c']},J:{x:1010,y:315,t:'MAX',kids:['l0c','l2c']}},leaves:{l2x:{x:265,y:315,v:2},l3x:{x:475,y:315,v:3},l1x:{x:665,y:315,v:1},l0a:{x:65,y:500,v:0},l2a:{x:120,y:500,v:2},l1a:{x:175,y:500,v:1},l4:{x:325,y:500,v:4},l3a:{x:375,y:500,v:3},l1b:{x:535,y:500,v:1},l0b:{x:585,y:500,v:0},l3b:{x:755,y:500,v:3},l2b:{x:810,y:500,v:2},l3c:{x:865,y:500,v:3},l0c:{x:985,y:500,v:0},l2c:{x:1035,y:500,v:2}}}
};
let nodes,leaves,parent,S,steps=[],idx=0,current='one';
const inf=x=>x===Infinity?'∞':x===-Infinity?'−∞':String(x);
const el=id=>document.querySelector(id), E={badge:el('#abStepBadge'),title:el('#abStepTitle'),action:el('#abAction'),explain:el('#abExplanation'),eq:el('#abEquation'),teach:el('#abTeachingPoint'),root:el('#abRootBest'),seen:el('#abLeavesSeen'),pruned:el('#abLeavesPruned'),bar:el('#abProgressBar'),next:el('#abNext'),prev:el('#abPrev'),reset:el('#abReset')};
function fresh(){const st={};Object.keys(nodes).forEach(id=>st[id]={a:-Infinity,b:Infinity,v:null,status:'idle'});return {n:st,seen:new Set(),pruned:new Set(),active:null,edge:null,dir:null,returnVal:null,leavesSeen:0,leavesPruned:0,title:'Start at the root',action:'Initialize alpha–beta search',explain:'The root is a MAX node. It begins with α = −∞ and β = +∞.',eq:'v = −∞, α = −∞, β = +∞',teach:'Bounds are maintained at decision nodes; terminal utilities return upward from leaves.'};}
function snap(meta={}){steps.push({...S,...meta,n:Object.fromEntries(Object.entries(S.n).map(([k,v])=>[k,{...v}])),seen:new Set(S.seen),pruned:new Set(S.pruned)});}
function setMeta(title,action,explain,eq,teach){Object.assign(S,{title,action,explain,eq,teach});}
function enter(id,a,b,from){S.n[id].a=a;S.n[id].b=b;S.n[id].v=nodes[id].t==='MAX'?-Infinity:Infinity;S.n[id].status='active';S.active=id;S.edge=from?[from,id]:null;S.dir='down';S.returnVal=null;setMeta(`Enter ${id} (${nodes[id].t})`,`Pass bounds downward to ${id}`,`${id} inherits α = ${inf(a)} and β = ${inf(b)} from its parent.`,`v = ${inf(S.n[id].v)}, α = ${inf(a)}, β = ${inf(b)}`,'α and β are bounds on decision nodes; they are not the node’s minimax value.');snap();}
function leaf(id,p){S.active=id;S.edge=[p,id];S.dir='leaf';S.seen.add(id);S.leavesSeen++;setMeta(`Evaluate leaf ${leaves[id].v}`,`Terminal utility = ${leaves[id].v}`,`We simply read the terminal utility ${leaves[id].v}. No α/β box is needed at the leaf. The utility now returns upward to ${p}.`,`utility = ${leaves[id].v}  →  return ${leaves[id].v}`,'Leaves provide fixed utilities. α and β matter for the internal decision nodes that decide whether more leaves need to be visited.');snap();}
function update(id,child,val){let n=S.n[id],oldv=n.v,olda=n.a,oldb=n.b;if(nodes[id].t==='MAX'){n.v=Math.max(n.v,val);n.a=Math.max(n.a,n.v)}else{n.v=Math.min(n.v,val);n.b=Math.min(n.b,n.v)}S.active=id;S.edge=[id,child];S.dir='up';S.returnVal=val;setMeta(`${child} returns ${val} to ${id}`,`${id} updates its value`,nodes[id].t==='MAX'?`MAX chooses the larger value. v: ${inf(oldv)} → ${n.v}; α: ${inf(olda)} → ${inf(n.a)}.`:`MIN chooses the smaller value. v: ${inf(oldv)} → ${n.v}; β: ${inf(oldb)} → ${inf(n.b)}.`,nodes[id].t==='MAX'?`v=max(${inf(oldv)},${val})=${n.v}; α=max(${inf(olda)},${n.v})=${inf(n.a)}`:`v=min(${inf(oldv)},${val})=${n.v}; β=min(${inf(oldb)},${n.v})=${inf(n.b)}`,n.a>=n.b?'The bounds have crossed: α ≥ β. A cutoff is now possible.':'No cutoff yet: α < β, so the search continues.');snap();}
function markPruned(id){S.pruned.add(id);if(leaves[id])S.leavesPruned++;if(nodes[id]){S.n[id].status='pruned';nodes[id].kids.forEach(markPruned)}}
function prune(ids,at){ids.forEach(markPruned);S.active=at;S.edge=null;S.dir=null;setMeta(`✂ Cutoff at ${at}`,`Prune the remaining branch${ids.length>1?'es':''}`,`At ${at}, α = ${inf(S.n[at].a)} and β = ${inf(S.n[at].b)}. Since α ≥ β, the remaining children cannot change the ancestor’s decision.`,`α = ${inf(S.n[at].a)} ≥ β = ${inf(S.n[at].b)}  ⇒  PRUNE`,'Alpha–beta saves work without changing the minimax answer.');snap();}
function done(id,to){S.n[id].status='done';S.active=id;S.edge=to?[to,id]:null;S.dir=to?'up':null;S.returnVal=S.n[id].v;setMeta(`${id} is complete: value ${S.n[id].v}`,`Return ${S.n[id].v}${to?' to '+to:''}`,`${id} has finished evaluating every child that could matter. Its minimax value is ${S.n[id].v}.`,`value(${id}) = ${S.n[id].v}`,to?'The computed node value now propagates upward.':'The root value is the minimax decision value.');snap();return S.n[id].v;}
function search(id,a,b,to){enter(id,a,b,to);let n=S.n[id],kids=nodes[id].kids;for(let i=0;i<kids.length;i++){let k=kids[i],val;if(leaves[k]){leaf(k,id);val=leaves[k].v}else val=search(k,n.a,n.b,id);update(id,k,val);if(n.a>=n.b&&i<kids.length-1){prune(kids.slice(i+1),id);break}}return done(id,to);}
function build(which){current=which;nodes=EXAMPLES[which].nodes;leaves=EXAMPLES[which].leaves;parent={};Object.entries(nodes).forEach(([p,n])=>n.kids.forEach(k=>parent[k]=p));steps=[];S=fresh();snap();search('R',-Infinity,Infinity,null);idx=0;svg.setAttribute('viewBox',EXAMPLES[which].viewBox);document.querySelectorAll('.ab-example-tab').forEach(b=>{const on=b.dataset.abExample===which;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});render();}
function edgeKey(a,b){return `${a}-${b}`}
function render(){let s=steps[idx],parts=[];Object.entries(nodes).forEach(([p,n])=>n.kids.forEach(k=>{let q=leaves[k]||nodes[k],cls='ab-edge';if(s.pruned.has(k)||s.pruned.has(p))cls+=' pruned';if(s.edge&&edgeKey(...s.edge)===edgeKey(p,k)){if(s.dir==='down')cls+=' active-down';else if(s.dir==='up')cls+=' active-up';else if(s.dir==='leaf')cls+=' active-leaf'}parts.push(`<line class="${cls}" x1="${n.x}" y1="${n.y+27}" x2="${q.x}" y2="${q.y-25}"/>`)}));
Object.entries(nodes).forEach(([id,n])=>{let st=s.n[id],cl='ab-node '+(s.active===id?'active ':'')+(st.status==='done'?'done ':'')+(s.pruned.has(id)?'pruned':'');let v=st.v===null?'—':inf(st.v);parts.push(`<g class="${cl}" transform="translate(${n.x},${n.y})"><circle class="node-circle" r="27"/><text class="node-name" y="-2">${id}</text><text class="node-type" y="14">${n.t}</text><rect class="ab-bounds-box" x="-52" y="36" width="104" height="48" rx="9"/><text class="ab-a-text" x="-25" y="55">α ${inf(st.a)}</text><text class="ab-b-text" x="25" y="55">β ${inf(st.b)}</text><text class="ab-v-text" y="75">v ${v}</text></g>`)});
Object.entries(leaves).forEach(([id,l])=>{let cl='ab-leaf '+(s.seen.has(id)?'seen ':'')+(s.active===id?'active ':'')+(s.pruned.has(id)?'pruned':'');parts.push(`<g class="${cl}" transform="translate(${l.x},${l.y})"><circle r="24"/><text y="6">${l.v}</text>${s.pruned.has(id)?'<path class="ab-prune-x" d="M-17,-17 L17,17 M17,-17 L-17,17"/>':''}</g>`)});
if(s.edge){let[a,b]=s.edge,A=nodes[a]||leaves[a],B=nodes[b]||leaves[b],x=(A.x+B.x)/2,y=(A.y+B.y)/2;if(s.dir==='down')parts.push(`<text class="ab-flow-label ab-flow-down" x="${x}" y="${y-8}">α, β ↓</text>`);else if(s.dir==='leaf')parts.push(`<text class="ab-flow-label ab-flow-visit" x="${x}" y="${y-8}">visit ↓</text>`);else parts.push(`<g transform="translate(${x},${y-8})"><circle class="ab-return-bubble" r="17"/><text class="ab-return-text" y="5">${s.returnVal}</text></g>`)}
svg.innerHTML=parts.join('');E.badge.textContent=`Step ${idx} / ${steps.length-1}`;E.title.textContent=s.title;E.action.textContent=s.action;E.explain.textContent=s.explain;E.eq.textContent=s.eq;E.teach.textContent=s.teach;let rv=s.n.R.v;E.root.textContent=rv===null||rv===-Infinity?'—':rv;E.seen.textContent=`${s.leavesSeen} / ${Object.keys(leaves).length}`;E.pruned.textContent=s.leavesPruned;E.bar.style.width=`${idx/(steps.length-1)*100}%`;E.prev.disabled=idx===0;E.next.disabled=idx===steps.length-1;E.next.textContent=idx===steps.length-1?'Complete ✓':'Next step →';}
E.next.addEventListener('click',()=>{if(idx<steps.length-1){idx++;render()}});E.prev.addEventListener('click',()=>{if(idx>0){idx--;render()}});E.reset.addEventListener('click',()=>{idx=0;render()});document.querySelectorAll('.ab-example-tab').forEach(b=>b.addEventListener('click',()=>build(b.dataset.abExample)));build('one');
})();
