(() => {
  'use strict';
  const ROWS=12,COLS=18;
  const key=([r,c])=>`${r},${c}`;
  const parse=(k)=>k.split(',').map(Number);
  const distances={
    zero:()=>0,
    manhattan:(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]),
    euclidean:(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),
    chebyshev:(a,b)=>Math.max(Math.abs(a[0]-b[0]),Math.abs(a[1]-b[1])),
    weighted:(a,b)=>1.7*(Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]))
  };
  function makeWalls(){const walls=new Set();for(let r=1;r<10;r++)if(r!==7)walls.add(`${r},5`);for(let c=5;c<16;c++)if(c!==12)walls.add(`4,${c}`);for(let r=5;r<12;r++)if(r!==9)walls.add(`${r},14`);return walls;}
  function search(start,goal,walls,type,diagonal){const frontier=[{cell:start,g:0,h:distances[type](start,goal)}],best=new Map([[key(start),0]]),parent=new Map(),steps=[];const dirs=diagonal?[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]]:[[-1,0],[1,0],[0,-1],[0,1]];const closed=new Set();while(frontier.length){frontier.sort((a,b)=>(a.g+a.h)-(b.g+b.h));const node=frontier.shift(),k=key(node.cell);if(closed.has(k))continue;closed.add(k);steps.push({current:k,explored:[...closed],frontier:frontier.map(x=>key(x.cell)),g:node.g,h:node.h});if(k===key(goal)){const path=[];let cur=k;while(cur){path.unshift(cur);cur=parent.get(cur);}steps[steps.length-1].path=path;steps[steps.length-1].found=true;return {steps,cost:node.g,expanded:closed.size,path};}for(const[dR,dC]of dirs){const n=[node.cell[0]+dR,node.cell[1]+dC],nk=key(n);if(n[0]<0||n[0]>=ROWS||n[1]<0||n[1]>=COLS||walls.has(nk))continue;const step=dR&&dC?Math.SQRT2:1,g=node.g+step;if(g<(best.get(nk)??Infinity)){best.set(nk,g);parent.set(nk,k);frontier.push({cell:n,g,h:distances[type](n,goal)});}}}return {steps,cost:null,expanded:closed.size,path:[]};}
  function init(){const root=document.getElementById('heuristicGridRoot');if(!root||root.dataset.ready)return;root.dataset.ready='true';root.innerHTML=`
    <div class="heuristic-lab-layout"><aside class="heuristic-control-card"><p class="eyebrow">Grid navigation</p><h2>Match the heuristic to movement</h2><label>Movement<select id="hgMovement"><option value="four">Four directions</option><option value="eight">Eight directions</option></select></label><label>Heuristic<select id="hgHeuristic"><option value="zero">Zero</option><option value="manhattan" selected>Manhattan</option><option value="euclidean">Euclidean</option><option value="chebyshev">Chebyshev</option><option value="weighted">Weighted Manhattan</option></select></label><label>Animation speed<input id="hgSpeed" type="range" min="10" max="180" value="95"></label><div class="button-grid"><button id="hgRun" class="primary-button" type="button">Run A*</button><button id="hgStep" type="button">Next step</button><button id="hgPause" type="button">Pause</button><button id="hgReset" type="button">Reset</button></div><div class="heuristic-teaching-note" id="hgMessage">Manhattan distance naturally matches four-directional movement.</div></aside><section><div id="hgGrid" class="heuristic-grid"></div><div class="metrics-grid heuristic-metrics"><article class="metric-card"><span>Expanded</span><strong id="hgExpanded">0</strong></article><article class="metric-card"><span>Frontier</span><strong id="hgFrontier">0</strong></article><article class="metric-card"><span>Current g / h / f</span><strong id="hgScores">—</strong></article><article class="metric-card"><span>Path cost</span><strong id="hgCost">—</strong></article></div><article class="heuristic-explanation-box"><h3>Interpretation</h3><p id="hgExplanation">Straight-line closeness is not always the same as reachable closeness when walls intervene.</p></article></section></div>`;
    const el={grid:root.querySelector('#hgGrid'),movement:root.querySelector('#hgMovement'),heuristic:root.querySelector('#hgHeuristic'),speed:root.querySelector('#hgSpeed'),expanded:root.querySelector('#hgExpanded'),frontier:root.querySelector('#hgFrontier'),scores:root.querySelector('#hgScores'),cost:root.querySelector('#hgCost'),message:root.querySelector('#hgMessage'),explanation:root.querySelector('#hgExplanation')};const start=[10,1],goal=[1,16],walls=makeWalls();let result=null,index=-1,timer=null;
    function render(step){const explored=new Set(step?.explored||[]),frontier=new Set(step?.frontier||[]),path=new Set(step?.path||[]);el.grid.style.setProperty('--heuristic-cols',COLS);el.grid.innerHTML='';for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const k=`${r},${c}`,cell=document.createElement('div');cell.className='heuristic-grid-cell';if(walls.has(k))cell.classList.add('wall');else if(explored.has(k))cell.classList.add('explored');if(frontier.has(k))cell.classList.add('frontier');if(path.has(k))cell.classList.add('path');if(step?.current===k)cell.classList.add('current');if(k===key(start)){cell.classList.add('start');cell.textContent='S';}if(k===key(goal)){cell.classList.add('goal');cell.textContent='G';}el.grid.append(cell);}el.expanded.textContent=step?.explored.length||0;el.frontier.textContent=step?.frontier.length||0;el.scores.textContent=step?`${step.g.toFixed(1)} / ${step.h.toFixed(1)} / ${(step.g+step.h).toFixed(1)}`:'—';el.cost.textContent=step?.found?result.cost.toFixed(1):'—';}
    function stop(){if(timer)clearInterval(timer);timer=null;}
    function reset(){stop();result=search(start,goal,walls,el.heuristic.value,el.movement.value==='eight');index=-1;render();el.message.textContent='Predict which region A* will explore first.';el.explanation.textContent=el.movement.value==='four'?'For four-direction movement, Manhattan distance reflects the unobstructed grid cost.':'With diagonal movement, Chebyshev or Euclidean distance better reflects the movement model.';}
    function next(){if(index>=result.steps.length-1){stop();return;}index++;render(result.steps[index]);if(result.steps[index].found){el.message.textContent=`Goal found after expanding ${result.expanded} cells.`;stop();}}
    root.querySelector('#hgRun').addEventListener('click',()=>{stop();timer=setInterval(next,Math.max(15,200-Number(el.speed.value)));});root.querySelector('#hgStep').addEventListener('click',()=>{stop();next();});root.querySelector('#hgPause').addEventListener('click',stop);root.querySelector('#hgReset').addEventListener('click',reset);el.heuristic.addEventListener('change',reset);el.movement.addEventListener('change',reset);reset();
  }
  window.addEventListener('heuristiclab:ready',init);if(document.readyState!=='loading')init();
})();
