(() => {
  'use strict';
  const ROWS=12,COLS=18;
  const key=([r,c])=>`${r},${c}`;
  const distances={
    zero:()=>0,
    manhattan:(a,b)=>Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]),
    euclidean:(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]),
    chebyshev:(a,b)=>Math.max(Math.abs(a[0]-b[0]),Math.abs(a[1]-b[1])),
    weighted:(a,b)=>1.7*(Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1]))
  };
  const heuristicInfo={
    zero:{title:'Zero heuristic',formula:'h(n)=0',meaning:'It makes no estimate of the remaining distance. A* therefore ranks nodes using only g(n), so it behaves exactly like Uniform-Cost Search.',best:'Useful as a baseline and always admissible.',warning:'It gives no directional guidance and usually expands many cells.'},
    manhattan:{title:'Manhattan distance',formula:'h(n)=|Δrow|+|Δcolumn|',meaning:'It counts how many horizontal plus vertical moves would be required on an empty grid. The name comes from travelling along rectangular city blocks.',best:'Natural for four-direction movement when every horizontal or vertical step costs 1.',warning:'With diagonal moves, it may overestimate because one diagonal can replace two axis-aligned moves.'},
    euclidean:{title:'Euclidean distance',formula:'h(n)=√(Δrow²+Δcolumn²)',meaning:'It is the straight-line distance from the current cell to the goal—the length of the direct geometric line between them.',best:'Natural when movement can occur in any direction, or when diagonal movement costs √2.',warning:'On a four-direction grid it is admissible but often weaker than Manhattan because the robot cannot actually move along the straight line.'},
    chebyshev:{title:'Chebyshev distance',formula:'h(n)=max(|Δrow|,|Δcolumn|)',meaning:'It counts the minimum number of king-like moves on an empty grid when horizontal, vertical and diagonal moves all cost the same.',best:'Natural for eight-direction movement when a diagonal move costs the same as a straight move.',warning:'If diagonal moves cost √2, Chebyshev remains safe but underestimates more than an octile-style estimate.'},
    weighted:{title:'Weighted Manhattan',formula:'h(n)=1.7×(|Δrow|+|Δcolumn|)',meaning:'It deliberately magnifies the ordinary Manhattan estimate so that A* trusts the goal direction more strongly.',best:'Can reduce expansions when a quick solution matters more than guaranteed optimality.',warning:'Because it can exceed the true remaining cost, it is generally inadmissible and may return a non-optimal path.'}
  };
  function makeWalls(){const walls=new Set();for(let r=1;r<10;r++)if(r!==7)walls.add(`${r},5`);for(let c=5;c<16;c++)if(c!==12)walls.add(`4,${c}`);for(let r=5;r<12;r++)if(r!==9)walls.add(`${r},14`);return walls;}
  function search(start,goal,walls,type,diagonal){const frontier=[{cell:start,g:0,h:distances[type](start,goal)}],best=new Map([[key(start),0]]),parent=new Map(),steps=[];const dirs=diagonal?[[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]]:[[-1,0],[1,0],[0,-1],[0,1]];const closed=new Set();while(frontier.length){frontier.sort((a,b)=>(a.g+a.h)-(b.g+b.h));const node=frontier.shift(),k=key(node.cell);if(closed.has(k))continue;closed.add(k);steps.push({current:k,explored:[...closed],frontier:frontier.map(x=>key(x.cell)),g:node.g,h:node.h});if(k===key(goal)){const path=[];let cur=k;while(cur){path.unshift(cur);cur=parent.get(cur);}steps[steps.length-1].path=path;steps[steps.length-1].found=true;return {steps,cost:node.g,expanded:closed.size,path};}for(const[dR,dC]of dirs){const n=[node.cell[0]+dR,node.cell[1]+dC],nk=key(n);if(n[0]<0||n[0]>=ROWS||n[1]<0||n[1]>=COLS||walls.has(nk))continue;const step=dR&&dC?Math.SQRT2:1,g=node.g+step;if(g<(best.get(nk)??Infinity)){best.set(nk,g);parent.set(nk,k);frontier.push({cell:n,g,h:distances[type](n,goal)});}}}return {steps,cost:null,expanded:closed.size,path:[]};}
  function init(){const root=document.getElementById('heuristicGridRoot');if(!root||root.dataset.ready)return;root.dataset.ready='true';root.innerHTML=`
    <section class="hg-lesson-hero"><p class="eyebrow">Grid heuristics</p><h2>A heuristic estimates the cheapest remaining cost</h2><p>For a cell <strong>n</strong>, the heuristic <strong>h(n)</strong> estimates how much movement cost is still needed to reach the goal. It does not include the cost already paid and it normally ignores some difficulty—such as walls—to remain cheap to compute. The estimate is meaningful only relative to the allowed movement model.</p></section>
    <section class="hg-movement-grid">
      <article><h3>Four-direction movement</h3><div class="hg-move-icons">↑ ↓ ← →</div><p>The robot can move only up, down, left or right. Each move costs 1. A diagonal displacement therefore requires two moves.</p></article>
      <article><h3>Eight-direction movement</h3><div class="hg-move-icons">↖ ↑ ↗ ← → ↙ ↓ ↘</div><p>The robot may also move diagonally. Here a diagonal costs √2, corresponding to its geometric length.</p></article>
      <article><h3>Walls and obstacles</h3><div class="hg-move-icons">S ▰ ▰ G</div><p>A distance heuristic usually ignores walls. It is therefore an optimistic lower bound: actual reachable distance can be larger than geometric distance.</p></article>
    </section>
    <section class="hg-heuristic-guide"><h2>What does each heuristic mean?</h2><div class="hg-guide-grid">
      ${Object.entries(heuristicInfo).map(([id,x])=>`<article data-guide="${id}"><h3>${x.title}</h3><code>${x.formula}</code><p>${x.meaning}</p><p><strong>Good choice:</strong> ${x.best}</p><p><strong>Limitation:</strong> ${x.warning}</p></article>`).join('')}
    </div></section>
    <div class="heuristic-lab-layout"><aside class="heuristic-control-card"><p class="eyebrow">Interactive experiment</p><h2>Match heuristic to movement</h2><label>Movement model<select id="hgMovement"><option value="four">Four directions (cost 1)</option><option value="eight">Eight directions (diagonal cost √2)</option></select></label><label>Heuristic<select id="hgHeuristic"><option value="zero">Zero</option><option value="manhattan" selected>Manhattan</option><option value="euclidean">Euclidean</option><option value="chebyshev">Chebyshev</option><option value="weighted">Weighted Manhattan</option></select></label><label>Animation speed<input id="hgSpeed" type="range" min="10" max="180" value="95"></label><div class="button-grid"><button id="hgRun" class="primary-button" type="button">Run A*</button><button id="hgStep" type="button">Next step</button><button id="hgPause" type="button">Pause</button><button id="hgReset" type="button">Reset</button></div><div class="heuristic-teaching-note" id="hgMessage"></div></aside><section><div id="hgGrid" class="heuristic-grid"></div><div class="hg-grid-legend"><span><i class="start"></i>Start</span><span><i class="goal"></i>Goal</span><span><i class="wall"></i>Wall</span><span><i class="frontier"></i>Frontier</span><span><i class="explored"></i>Expanded</span><span><i class="path"></i>Final path</span></div><div class="metrics-grid heuristic-metrics"><article class="metric-card"><span>Expanded</span><strong id="hgExpanded">0</strong></article><article class="metric-card"><span>Frontier</span><strong id="hgFrontier">0</strong></article><article class="metric-card"><span>Current g / h / f</span><strong id="hgScores">—</strong></article><article class="metric-card"><span>Path cost</span><strong id="hgCost">—</strong></article></div><article class="heuristic-explanation-box"><h3 id="hgExplainTitle">Interpretation</h3><p id="hgExplanation"></p><div id="hgSuitability" class="hg-suitability"></div></article></section></div>`;
    const el={grid:root.querySelector('#hgGrid'),movement:root.querySelector('#hgMovement'),heuristic:root.querySelector('#hgHeuristic'),speed:root.querySelector('#hgSpeed'),expanded:root.querySelector('#hgExpanded'),frontier:root.querySelector('#hgFrontier'),scores:root.querySelector('#hgScores'),cost:root.querySelector('#hgCost'),message:root.querySelector('#hgMessage'),explanation:root.querySelector('#hgExplanation'),title:root.querySelector('#hgExplainTitle'),suitability:root.querySelector('#hgSuitability')};const start=[10,1],goal=[1,16],walls=makeWalls();let result=null,index=-1,timer=null;
    function render(step){const explored=new Set(step?.explored||[]),frontier=new Set(step?.frontier||[]),path=new Set(step?.path||[]);el.grid.style.setProperty('--heuristic-cols',COLS);el.grid.innerHTML='';for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){const k=`${r},${c}`,cell=document.createElement('div');cell.className='heuristic-grid-cell';if(walls.has(k))cell.classList.add('wall');else if(explored.has(k))cell.classList.add('explored');if(frontier.has(k))cell.classList.add('frontier');if(path.has(k))cell.classList.add('path');if(step?.current===k)cell.classList.add('current');if(k===key(start)){cell.classList.add('start');cell.textContent='S';}if(k===key(goal)){cell.classList.add('goal');cell.textContent='G';}el.grid.append(cell);}el.expanded.textContent=step?.explored.length||0;el.frontier.textContent=step?.frontier.length||0;el.scores.textContent=step?`${step.g.toFixed(1)} / ${step.h.toFixed(1)} / ${(step.g+step.h).toFixed(1)}`:'—';el.cost.textContent=step?.found?result.cost.toFixed(1):'—';}
    function compatibility(){const h=el.heuristic.value,m=el.movement.value,info=heuristicInfo[h];let status='Reasonable but not necessarily strongest',klass='neutral',detail='';if(h==='zero'){status='Always safe, but uninformed';klass='safe';detail='A* becomes UCS, so movement geometry is ignored.';}else if(h==='manhattan'&&m==='four'){status='Excellent match';klass='safe';detail='The empty-grid estimate exactly equals the four-direction cost when no walls block the route.';}else if(h==='manhattan'&&m==='eight'){status='Can overestimate';klass='risk';detail='A diagonal can replace one horizontal and one vertical move, so Manhattan may be larger than the true cost.';}else if(h==='euclidean'&&m==='eight'){status='Excellent geometric match';klass='safe';detail='Straight-line distance is a lower bound when diagonal steps cost √2.';}else if(h==='euclidean'&&m==='four'){status='Safe but less informed';klass='neutral';detail='It underestimates because the robot cannot follow the direct diagonal line.';}else if(h==='chebyshev'&&m==='eight'){status='Safe, but assumes cheap diagonals';klass='neutral';detail='It exactly matches eight-direction movement only when diagonal and straight steps have equal cost. With √2 diagonals it is optimistic but weaker.';}else if(h==='chebyshev'&&m==='four'){status='Safe but weak';klass='neutral';detail='It ignores part of the required horizontal-plus-vertical travel.';}else if(h==='weighted'){status='Fast guidance, no optimality guarantee';klass='risk';detail='Multiplying by 1.7 can make the estimate exceed the true remaining cost.';}
      el.title.textContent=info.title;el.explanation.innerHTML=`<strong>${info.formula}</strong>. ${info.meaning}`;el.suitability.className=`hg-suitability ${klass}`;el.suitability.innerHTML=`<strong>${status}.</strong> ${detail}`;el.message.innerHTML=`<strong>Before running:</strong> predict whether this heuristic will tightly follow the goal, explore broadly, or risk misleading A*.`;document.querySelectorAll('#heuristicGridRoot [data-guide]').forEach(x=>x.classList.toggle('active',x.dataset.guide===h));}
    function stop(){if(timer)clearInterval(timer);timer=null;}
    function reset(){stop();result=search(start,goal,walls,el.heuristic.value,el.movement.value==='eight');index=-1;render();compatibility();}
    function next(){if(index>=result.steps.length-1){stop();return;}index++;render(result.steps[index]);if(result.steps[index].found){el.message.innerHTML=`<strong>Result:</strong> goal found after expanding ${result.expanded} cells with path cost ${result.cost.toFixed(1)}. Compare another heuristic to see whether the same optimal cost is preserved with fewer expansions.`;stop();}}
    root.querySelector('#hgRun').addEventListener('click',()=>{stop();timer=setInterval(next,Math.max(15,200-Number(el.speed.value)));});root.querySelector('#hgStep').addEventListener('click',()=>{stop();next();});root.querySelector('#hgPause').addEventListener('click',stop);root.querySelector('#hgReset').addEventListener('click',reset);el.heuristic.addEventListener('change',reset);el.movement.addEventListener('change',reset);reset();
  }
  window.addEventListener('heuristiclab:ready',init);if(document.readyState!=='loading')init();
})();
