(() => {
  'use strict';
  const scenarios=[
    {id:'route',title:'Road-route planning',problem:'Find the minimum driving time from one city to another.',state:'Current road intersection',cost:'Travel time already spent',goal:'Destination city',candidates:[
      {name:'Straight-line distance',quality:'good',why:'A useful lower bound when converted conservatively to time using a maximum possible speed. It captures geographic progress.'},
      {name:'Estimated remaining driving time',quality:'best',why:'Potentially more informed because it can reflect road class and speed, but it must not overestimate if optimality is required.'},
      {name:'Number of roads already travelled',quality:'bad',why:'This describes the past, so it belongs to g(n), not h(n). It says little about remaining effort.'},
      {name:'Alphabetical distance between city names',quality:'bad',why:'It has no relationship to road cost and gives arbitrary guidance.'}
    ],lesson:'A heuristic must estimate remaining cost in the same units as the objective. If path cost is time, a distance-only heuristic should be converted carefully.'},
    {id:'puzzle',title:'8-puzzle',problem:'Move tiles until the board matches the goal arrangement.',state:'Current tile arrangement',cost:'Number of moves already made',goal:'Goal arrangement',candidates:[
      {name:'Number of misplaced tiles',quality:'good',why:'Every misplaced tile must move at least once. It is admissible, but ignores how far each tile is displaced.'},
      {name:'Sum of Manhattan distances',quality:'best',why:'Counts the minimum row/column displacement of every tile while ignoring blocking. It dominates misplaced tiles.'},
      {name:'Tile values currently in the top row',quality:'bad',why:'The numeric labels are identities, not movement costs. Their sum is unrelated to closeness to the goal.'},
      {name:'Twice the Manhattan distance',quality:'risky',why:'It is more aggressive, but may overestimate the true number of remaining moves and lose optimality.'}
    ],lesson:'Relaxing constraints often produces a heuristic: Manhattan distance imagines that each tile can move toward its target without other tiles blocking it.'},
    {id:'robot',title:'Warehouse robot',problem:'Reach a shelf while avoiding obstacles and minimizing energy.',state:'Robot position, orientation and load',cost:'Energy already consumed',goal:'Target shelf',candidates:[
      {name:'Straight-line distance to shelf',quality:'good',why:'Cheap and optimistic, but ignores walls, turning, and load.'},
      {name:'Distance plus minimum required turns',quality:'best',why:'Uses more of the state and can be more informed if each term is a proven lower bound on energy.'},
      {name:'Distance from the starting dock',quality:'bad',why:'Measures progress already made rather than energy still required.'},
      {name:'Shortest path through walls computed exactly',quality:'poortradeoff',why:'Perfect as h(n), but if it requires solving the original search problem at every node, the heuristic is too expensive to be useful.'}
    ],lesson:'A stronger heuristic is not automatically better overall. Its search savings must justify its computation cost.'},
    {id:'schedule',title:'Job-shop scheduling',problem:'Complete all remaining jobs as early as possible on limited machines.',state:'Finished jobs, machine availability and remaining operations',cost:'Elapsed schedule time',goal:'All jobs completed',candidates:[
      {name:'Longest remaining processing chain',quality:'good',why:'The schedule cannot finish before its longest precedence chain finishes, so this is a lower bound.'},
      {name:'Total remaining work ÷ number of machines',quality:'good',why:'Even with perfect balancing, machines need at least this much additional time.'},
      {name:'Maximum of both lower bounds',quality:'best',why:'Taking the maximum of admissible lower bounds is still admissible and dominates either bound alone.'},
      {name:'Total remaining processing time',quality:'risky',why:'It assumes jobs run sequentially and can overestimate when machines work in parallel.'}
    ],lesson:'Complex problems often combine multiple lower bounds. The maximum of admissible heuristics is admissible and at least as informed as each component.'},
    {id:'game',title:'Game playing',problem:'Choose moves that lead to a winning or high-value position.',state:'Current game board',cost:'Usually not a shortest-path cost',goal:'Win or maximize utility',candidates:[
      {name:'Material advantage',quality:'good',why:'In chess-like games, piece values provide a fast estimate of position strength.'},
      {name:'Material + mobility + king safety',quality:'best',why:'Combines several features and usually evaluates positions better than material alone.'},
      {name:'Distance from pieces to one fixed corner',quality:'bad',why:'Unless the game objective depends on that corner, it is unrelated to winning.'},
      {name:'Exact win/loss from full search',quality:'poortradeoff',why:'Perfect evaluation would require solving the entire game tree—the computation the heuristic is meant to avoid.'}
    ],lesson:'In adversarial search, an evaluation function estimates utility rather than remaining path cost. Admissibility is usually not the central requirement.'}
  ];
  const labels={best:'Best fit',good:'Useful',bad:'Poor heuristic',risky:'May lose guarantee',poortradeoff:'Accurate but impractical'};
  function init(){const root=document.getElementById('heuristicRaceRoot');if(!root||root.dataset.ready)return;root.dataset.ready='true';root.innerHTML=`
    <section class="hr-design-hero"><p class="eyebrow">Heuristic design lab</p><h2>Different problems need different heuristics</h2><p>A heuristic is not simply “distance to the goal.” It is a problem-specific estimate derived from the state, the legal actions and the quantity being optimized. A good heuristic should be relevant, cheap to compute, and—when A* optimality matters—a lower bound on remaining cost.</p></section>
    <section class="hr-principles"><article><h3>1. Match the objective</h3><p>If path cost measures time, estimate remaining time. If it measures energy, estimate energy. Mixing units makes f(n)=g(n)+h(n) meaningless.</p></article><article><h3>2. Use a relaxed problem</h3><p>Ignore selected constraints—walls, conflicts or resource contention—so the easier problem gives a lower bound on the real one.</p></article><article><h3>3. Balance information and cost</h3><p>A perfect heuristic that is as expensive as solving the original problem provides no practical benefit.</p></article></section>
    <div class="hr-scenario-layout"><aside class="heuristic-control-card"><p class="eyebrow">Choose a problem</p><label>Problem domain<select id="hrScenario">${scenarios.map((s,i)=>`<option value="${i}">${s.title}</option>`).join('')}</select></label><div id="hrProblemSummary"></div><div class="heuristic-teaching-note"><strong>Class discussion:</strong> Which candidate estimates the remaining objective? Which one is safe? Which one is informative but still cheap?</div></aside><section><div id="hrCandidateGrid" class="hr-candidate-grid"></div><article class="heuristic-explanation-box"><h3>Design lesson</h3><p id="hrLesson"></p></article></section></div>
    <section class="hr-comparison-section"><h2>Why apparently intuitive heuristics can be poor</h2><div class="hr-mistake-grid"><article><h3>Uses past cost</h3><p>Features such as distance already travelled belong in <strong>g(n)</strong>. Reusing them in h(n) double-counts history instead of estimating the future.</p></article><article><h3>Ignores legal actions</h3><p>Straight-line distance is meaningful only when it is a lower bound under the actual movement rules and costs.</p></article><article><h3>Overestimates</h3><p>An aggressive estimate can focus search, but A* may then skip the optimal solution. This trade-off may be acceptable only when speed matters more than optimality.</p></article><article><h3>Costs too much</h3><p>The heuristic is evaluated at many nodes. Even a very accurate estimate may slow the complete search if each evaluation is expensive.</p></article></div></section>
    <section class="hr-recipe"><h2>A reusable recipe for inventing a heuristic</h2><ol><li>Define exactly what one state contains.</li><li>Identify the remaining objective that h(n) must estimate.</li><li>Remove one or more constraints to create an easier problem.</li><li>Use the optimal cost of that relaxed problem as a lower bound.</li><li>Check admissibility/consistency when optimal A* graph search is required.</li><li>Compare search reduction against heuristic computation time.</li></ol></section>`;
    const select=root.querySelector('#hrScenario'),summary=root.querySelector('#hrProblemSummary'),grid=root.querySelector('#hrCandidateGrid'),lesson=root.querySelector('#hrLesson');
    function render(){const s=scenarios[Number(select.value)];summary.innerHTML=`<h3>${s.title}</h3><p>${s.problem}</p><dl class="hr-state-model"><div><dt>State</dt><dd>${s.state}</dd></div><div><dt>g(n)</dt><dd>${s.cost}</dd></div><div><dt>Goal</dt><dd>${s.goal}</dd></div></dl>`;grid.innerHTML=s.candidates.map(c=>`<article class="hr-candidate ${c.quality}"><span>${labels[c.quality]}</span><h3>${c.name}</h3><p>${c.why}</p></article>`).join('');lesson.textContent=s.lesson;}
    select.addEventListener('change',render);render();
  }
  window.addEventListener('heuristiclab:ready',init);if(document.readyState!=='loading')init();
})();
