(function(root){
'use strict';
const alarm={nodes:['B','E','A','J','M'],parents:{B:[],E:[],A:['B','E'],J:['A'],M:['A']},cpt:{B:[.001],E:[.002],A:[.001,.29,.94,.95],J:[.05,.9],M:[.01,.7]}};
function probability(net,node,state){let i=0;for(const p of net.parents[node]) i=i*2+Number(state[p]);return net.cpt[node][i];}
function joint(net,s){return net.nodes.reduce((p,n)=>p*(s[n]?probability(net,n,s):1-probability(net,n,s)),1);}
function infer(net,q,evidence={}){const rows=[];let yes=0,no=0;for(let mask=0;mask<2**net.nodes.length;mask++){const s={};net.nodes.forEach((n,i)=>s[n]=Boolean(mask&(1<<i)));if(Object.entries(evidence).some(([n,v])=>s[n]!==v))continue;const p=joint(net,s);rows.push({state:s,p});if(s[q])yes+=p;else no+=p;}return {yes,no,total:yes+no,posterior:yes+no?yes/(yes+no):null,rows};}
function paths(net,x,y){const adj=Object.fromEntries(net.nodes.map(n=>[n,[]]));for(const n of net.nodes) for(const p of net.parents[n]){adj[p].push(n);adj[n].push(p);}const result=[];function visit(path){const n=path.at(-1);if(n===y){result.push(path);return;}for(const next of adj[n])if(!path.includes(next))visit([...path,next]);}visit([x]);return result;}
function assess(net,path,observed){const ancestors=new Set(observed);const todo=[...observed];while(todo.length)for(const p of net.parents[todo.pop()])if(!ancestors.has(p)){ancestors.add(p);todo.push(p);}const checks=[];for(let i=1;i<path.length-1;i++){const n=path[i];const collider=net.parents[n].includes(path[i-1])&&net.parents[n].includes(path[i+1]);const open=collider?ancestors.has(n):!observed.includes(n);checks.push({node:n,collider,open,reason:collider?(open?'Collider opened by observing it or a descendant.':'Unobserved collider blocks the path.'):(open?'Unobserved non-collider passes the path.':'Observed non-collider blocks the path.')});}return {path,checks,active:checks.every(c=>c.open)};}
const api={alarm,probability,joint,infer,paths,assess};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.ProbabilityEngine=api;
})(typeof window!=='undefined'?window:globalThis);
