'use strict';
const G=GridLab,$=id=>document.getElementById(id);
const sessions={grid:new G.Lab(42,'grid'),cliff:new G.Lab(42,'cliff')},savedSettings={};
let activeTab='grid',lab=sessions.grid,timer=null,busy=false,stop=false;
const configIDs=['alpha','gamma','epsilon','living','learning'];
function config(){const read=(id,lo,hi)=>Math.max(lo,Math.min(hi,Number($(id).value)||0));return {alpha:read('alpha',0,1),gamma:read('gamma',0,1),epsilon:read('epsilon',0,1),living:read('living',-1,1),learning:$('learning').checked};}
const f=v=>(Math.abs(v)<.0005?0:v).toFixed(3),short=v=>(Math.abs(v)<.005?0:v).toFixed(2);
function pause(){clearTimeout(timer);timer=null;stop=true;$('run').textContent='▶ Auto-play';}
function color(q){const t=Math.min(1,Math.abs(q)/(lab.map.id==='cliff'?(q<0?100:10):1));const a=[244,247,250],b=q>=0?[30,141,105]:[198,73,97];return `rgb(${a.map((v,i)=>Math.round(v+(b[i]-v)*t)).join(',')})`;}
function draw(){const M=lab.map,cliff=M.id==='cliff',viewWidth=72+M.width*162;const p=lab.last,policy=$('policy').checked;$('board').setAttribute('viewBox',`0 0 ${viewWidth} 550`);let svg=`<title>${M.name}</title><desc>${cliff?'Seven columns, three rows. Safe middle path from (1,1) to island (6,1), +10. Ocean above, below and to the left, -100.':'Four columns and three rows. Start (0,0), wall (1,1), exits +1 and -1.'}</desc>`;
const text=(x,y,t,sz=16,fill='#294156',weight=600)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${sz}" fill="${fill}" font-weight="${weight}">${t}</text>`;
for(let s=0;s<M.width*M.height;s++){const x=36+s%M.width*162,y=28+(2-Math.floor(s/M.width))*162,cx=x+75,cy=y+75;svg+=`<g data-state="${s}">`;
if(M.walls.includes(s)){svg+=`<rect x="${x}" y="${y}" width="150" height="150" rx="5" fill="#d3dae2"/>`;for(let k=16;k<140;k+=18)svg+=`<path d="M ${x+k} ${y+15} v 120" stroke="#c7cfd9" stroke-width="2"/>`;svg+=text(cx,cy+5,'WALL',12,'#788795',750);}
else if(s in M.exits){const q=lab.q[s][4],selected=p&&p.s===s,next=p&&p.next===s;svg+=`<rect x="${x}" y="${y}" width="150" height="150" rx="5" fill="${cliff?(M.exits[s]>0?'#e5f5dc':'#d9f1fa'):color(q)}" stroke="${selected?'#e3a72b':next?'#5687d5':'#cbd6df'}" stroke-width="${selected?4:next?2.5:1}"/><rect x="${x+9}" y="${y+9}" width="132" height="132" rx="2" fill="none" stroke="#a4b7bf"/>`;svg+=text(cx,y+38,(M.exits[s]>0?'+'+M.exits[s]:'−'+Math.abs(M.exits[s]))+(cliff?(M.exits[s]>0?' ISLAND':' OCEAN'):' EXIT'),15,!cliff&&Math.abs(q)>.6?'#ffffff':M.exits[s]>0?'#197b5b':'#a43d56',800);svg+=text(cx,y+69,'Q(exit)',11,!cliff&&Math.abs(q)>.6?'#edf7f0':'#416c81');svg+=text(cx,y+101,short(q),24,!cliff&&Math.abs(q)>.6?'#ffffff':q<0?'#a52e4e':'#233e51',750);if(cliff){if(M.exits[s]<0){for(const wy of [121,134])svg+=`<path d="M ${x+16} ${y+wy} q 10 -8 20 0 t 20 0 t 20 0 t 20 0 t 20 0 t 16 0" fill="none" stroke="#49aacb" stroke-width="3" opacity=".8"/>`;}else{svg+=`<ellipse cx="${cx}" cy="${y+132}" rx="52" ry="9" fill="#edcd86"/><path d="M ${x+84} ${y+129} L ${x+105} ${y+103} L ${x+128} ${y+129} Z" fill="#9bbcc0"/><path d="M ${x+97} ${y+113} L ${x+105} ${y+103} L ${x+114} ${y+113} L ${x+106} ${y+111} Z" fill="white"/><path d="M ${x+26} ${y+137} q 9 -5 18 0 t 18 0 t 18 0 t 18 0" fill="none" stroke="#66b3d0" stroke-width="2"/>`;}}}
else{const pts=[[[0,0],[150,0],[75,75]],[[150,0],[150,150],[75,75]],[[150,150],[0,150],[75,75]],[[0,150],[0,0],[75,75]]],places=[[75,31],[120,82],[75,135],[30,82]];
for(let a=0;a<4;a++){const q=lab.q[s][a],sel=p&&p.s===s&&p.a===a,next=false;svg+=`<polygon points="${pts[a].map(([dx,dy])=>`${x+dx},${y+dy}`).join(' ')}" fill="${color(q)}" stroke="${sel?'#e3a72b':next?'#5687d5':'#cbd6df'}" stroke-width="${sel?4:next?2.5:1}"/>`;svg+=text(x+places[a][0],y+places[a][1],short(q),short(q).length>5?12:17,Math.abs(q)>(cliff?(q<0?60:6):.6)?'#ffffff':'#294156',sel?800:600);}
if(p&&p.next===s){for(const a of p.bestNext){const center=pts[a].reduce((v,pt)=>[v[0]+pt[0]/3,v[1]+pt[1]/3],[0,0]);svg+=`<polygon class="bootstrap-outline" points="${pts[a].map(([dx,dy])=>`${x+center[0]+(dx-center[0])*.88},${y+center[1]+(dy-center[1])*.88}`).join(' ')}" fill="none" stroke="#3977e8" stroke-width="3" stroke-linejoin="round"/>`;}}
if(policy){const max=lab.maximum(s),best=lab.actions(s).filter(a=>lab.q[s][a]===max);svg+=text(cx,cy+(lab.s===s?35:7),best.map(a=>G.ARROWS[a]).join(''),17,Math.abs(max)>(cliff?(max<0?60:6):.6)?'#ffffff':'#2b638c',800);}}
svg+=text(x+12,y+148,`${s%M.width},${Math.floor(s/M.width)}`,8,'#778b97',500);if(s===lab.s){const ay=s in M.exits?y+121:cy;svg+=`<g class="robot-agent" transform="translate(${cx} ${ay}) scale(${s in M.exits?.72:1})"><title>Robot agent</title><path d="M 0 -15 v -7" stroke="#244c83" stroke-width="3"/><circle cx="0" cy="-23" r="3" fill="#ffc44d" stroke="white" stroke-width="1.5"/><rect x="-20" y="-7" width="40" height="14" rx="5" fill="#316ace" stroke="white" stroke-width="2"/><rect x="-16" y="-15" width="32" height="31" rx="9" fill="#599aff" stroke="white" stroke-width="2.5"/><rect x="-12" y="-10" width="24" height="18" rx="6" fill="#dff8ff"/><circle cx="-5" cy="-2" r="2.6" fill="#214669"/><circle cx="5" cy="-2" r="2.6" fill="#214669"/><path d="M -4 4 Q 0 8 4 4" fill="none" stroke="#214669" stroke-width="1.6" stroke-linecap="round"/><path d="M -7 18 h 4 M 3 18 h 4" stroke="#244c83" stroke-width="3" stroke-linecap="round"/></g>`;}
svg+='</g>';}
svg+=text(viewWidth/2,538,'N ↑     E →     S ↓     W ←   ·   Each triangle is one Q(s,a)',11,'#6c7e8f',500);$('board').innerHTML=svg;}
function render(){draw();$('boardTitle').textContent=lab.map.name;$('sceneNote').textContent=activeTab==='cliff'?'Cross the path to the +10 island. Ocean exits cost −100. No slips.':'Reach the +1 exit and avoid the −1 exit. No slips.';$('outcomeLabel').textContent=activeTab==='cliff'?'+10 island / −100 ocean':'+1 / −1 exits';$('exitRules').textContent=activeTab==='cliff'?'The +10 island and −100 ocean squares offer only Exit. Entering one gives the living reward; taking Exit gives its displayed reward and ends the episode.':'The +1 and −1 squares offer only Exit. Entering one gives the living reward; taking Exit gives +1 or −1 and ends the episode.';for(const id of ['grid','cliff']){$('tab-'+id).setAttribute('aria-selected',String(activeTab===id));$('tab-'+id).disabled=busy;}const p=lab.last;$('episode').textContent='Episode '+lab.episode;$('move').textContent='Move '+lab.steps;$('updates').textContent=lab.updates.toLocaleString();$('completed').textContent=lab.completed;$('return').textContent=short(lab.total);$('outcomes').textContent=`${lab.wins} / ${lab.losses}`;$('next').textContent=lab.over?'Start next episode →':'Take action + update →';$('stageLabel').textContent=p?(p.learning?'Updated automatically':'Move complete'):'Ready';$('stage1').className=p?'done':'active';$('stage2').className=p?'active':'';
if(p){const info=p.reason+(p.next===p.s?' · blocked: stayed in place':'');$('sample').innerHTML=`<div class="small">Observed transition (s, a, s′, r)</div><div class="tuple">${lab.label(p.s)} · ${G.ACTIONS[p.a]}<br>→ ${lab.label(p.next)} · r = ${short(p.reward)}</div><div class="small">${info}</div>`;for(const [id,v] of [['old',p.old],['reward',p.reward],['bootstrap',p.boot],['target',p.target]])$(id).textContent=f(v);
$('result').innerHTML=p.learning?`Updated Q(s,a)<b>${f(p.value)}</b>`:`Learning is off · Q unchanged<b>${f(p.old)}</b>`;$('calculation').innerHTML=`<div><b>sample</b> = ${f(p.reward)} + ${p.gamma} × ${f(p.boot)} = <b>${f(p.target)}</b></div><div><b>New Q</b> = (1 − ${p.alpha}) × (${f(p.old)}) + ${p.alpha} × (${f(p.target)}) = <b>${f(p.value)}</b></div>${p.next===G.TERMINAL?'<div>Terminal: max Q(s′,a′) = 0.</div>':''}${!p.learning?'<div>Formula shown only; learning is off.</div>':''}`;
$('status').textContent=lab.over?(lab.s===G.TERMINAL?`Episode finished at the ${p.reward>0?'+'+p.reward:p.reward} exit. Q-values are retained for the next episode.`:'500-move safety limit reached. This is a truncation, not a terminal reward; the update kept its bootstrap.'):`${p.learning?'Action taken and Q('+lab.label(p.s)+', '+G.ACTIONS[p.a]+') updated automatically.':'Move completed; Q-table frozen.'} Choose the next action.`;
}else{$('sample').innerHTML='<div class="small">Observed transition (s, a, s′, r)</div><div class="tuple">Waiting for a move…</div>';for(const id of ['old','reward','bootstrap','target'])$(id).textContent='—';$('result').textContent='Each action immediately updates its Q-value.';$('calculation').textContent='The calculation remains visible after every move.';$('status').textContent=lab.updates?'New episode, same learned Q-table. Choose an action.':'All Q-values start at zero. Take an action to move and learn in one step.';}
for(const id of configIDs)$(id).disabled=busy;for(const id of ['next','run','back','train','reset','csv','seed'])$(id).disabled=busy;$('back').disabled=busy||!lab.history.length;for(const [id,a] of [['north',0],['east',1],['south',2],['west',3],['exit',4]])$(id).disabled=busy||lab.over||!lab.actions(lab.s).includes(a);
$('log').innerHTML=lab.log.length?lab.log.slice(-12).reverse().map(t=>`<tr><td>${t.episode}</td><td>${lab.label(t.s)} ${G.ARROWS[t.a]}</td><td>${short(t.reward)}</td><td>${f(t.old)}</td><td>${f(t.learning?t.value:t.old)}${t.learning?'':' (frozen)'}</td></tr>`).join(''):'<tr><td colspan="5">Your first update will appear here.</td></tr>';}
function step(){if(busy)return;lab.tick(config());render();}
$('next').onclick=()=>{pause();step();};$('back').onclick=()=>{pause();lab.undo();render();};$('pause').onclick=pause;$('run').onclick=()=>{pause();stop=false;function tick(){step();$('run').textContent='● Playing';timer=setTimeout(tick,Number($('speed').value));}tick();};
for(const [id,a] of [['north',0],['east',1],['south',2],['west',3],['exit',4]])$(id).onclick=()=>{if($(id).disabled)return;pause();lab.act(config(),a);render();};
$('policy').onchange=render;
$('reset').onclick=()=>{pause();if(lab.log.length){if(!confirm('Clear all Q-values and start again?'))return;}lab=new G.Lab(Number($('seed').value)||0,activeTab);sessions[activeTab]=lab;$('trainStatus').textContent='Reset complete. Settings retained; Q-values are zero.';render();};
$('train').onclick=async()=>{pause();if(!config().learning){$('trainStatus').textContent='Turn on “Learn from moves” before fast training.';return;}busy=true;stop=false;render();let done=0;const c=config();try{while(done<100&&!stop){if(lab.over)lab.nextEpisode();while(!lab.over)lab.act(c);done++;$('trainStatus').textContent=`${done}/100 episodes trained · ${lab.truncated} truncations total`;render();await new Promise(resolve=>setTimeout(resolve,0));}$('trainStatus').textContent=`${stop?'Stopped':'Finished'}: ${done} episodes (including the current partial episode, if any). ${lab.truncated} total truncations.`;}finally{busy=false;render();}};
$('csv').onclick=()=>{let csv='episode,move,state_x,state_y,action,actual_direction,next_state,reward,old_q,target,new_q,learning\n';for(const t of lab.log)csv+=[t.episode,t.move,t.s%lab.map.width,Math.floor(t.s/lab.map.width),G.ACTIONS[t.a],G.ACTIONS[t.actual],t.next===-1?'TERMINAL':`${t.next%lab.map.width}:${Math.floor(t.next/lab.map.width)}`,t.reward,t.old,t.target,t.learning?t.value:t.old,t.learning].join(',')+'\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=activeTab+'-q-updates.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.addEventListener('keydown',ev=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','SUMMARY'].includes(ev.target.tagName)||ev.ctrlKey||ev.metaKey||ev.altKey)return;const id={ArrowUp:'north',ArrowRight:'east',ArrowDown:'south',ArrowLeft:'west',' ':'next',Backspace:'back'}[ev.key];if(id){ev.preventDefault();if(!$(id).disabled)$(id).click();}});
function switchTab(id){if(busy||id===activeTab)return;pause();savedSettings[activeTab]=Object.fromEntries([...configIDs,'seed','speed','policy'].map(k=>[k,{value:$(k).value,checked:$(k).checked}]));activeTab=id;lab=sessions[id];if(savedSettings[id])for(const [k,v] of Object.entries(savedSettings[id])){$(k).value=v.value;$(k).checked=v.checked;}else{for(const [k,v] of Object.entries({alpha:.5,gamma:.9,epsilon:.3,living:0,seed:42,speed:850}))$(k).value=v;$('learning').checked=true;$('policy').checked=false;}$('layout').className='layout '+(id==='cliff'?'cliff-layout':'');$('trainStatus').textContent='This tab has its own Q-table, episode history and settings.';render();}
$('tab-grid').onclick=()=>switchTab('grid');$('tab-cliff').onclick=()=>switchTab('cliff');
render();
