/* Minimal DOM stub tests logic; it is not a visual browser test. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'src/template.html'),'utf8'),els={};for(const m of html.matchAll(/\bid="([^"]+)"/g))els[m[1]]={value:'',checked:false,disabled:false,textContent:'',innerHTML:'',setAttribute(k,v){this[k]=v;},click(){this.onclick?.();}};
for(const [id,v] of Object.entries({alpha:'.5',gamma:'.9',epsilon:'.3',living:'0',seed:'42',speed:'850'}))els[id].value=v;els.learning.checked=true;let exportCount=0;
const scope={GridLab:require('../src/engine'),document:{getElementById:id=>{assert.ok(els[id],id);return els[id];},addEventListener(){},createElement:()=>({click:()=>exportCount++})},setTimeout,clearTimeout,confirm:()=>true,Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},console};vm.createContext(scope);vm.runInContext(fs.readFileSync(path.join(root,'src/app.js'),'utf8'),scope);const get=s=>vm.runInContext(s,scope);
(async()=>{assert.ok(els.board.innerHTML.includes('polygon'));els.living.value='-0.1';els.north.onclick();assert.equal(get('lab.s'),4);assert.equal(get('lab.updates'),1);assert.equal(get('lab.q[0][0]'),-.05);assert.equal(els.north.disabled,false);assert.ok(els.stageLabel.textContent.includes('automatically'));assert.ok(els.board.innerHTML.includes('robot-agent'));assert.ok(els.board.innerHTML.includes('bootstrap-outline'));assert.ok(els.calculation.innerHTML.includes('(1 − 0.5)'));if(process.env.SVG_PREVIEW)fs.writeFileSync(process.env.SVG_PREVIEW+'.initial.svg','<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="764" viewBox="0 0 720 550"><style>text{font-family:Arial,sans-serif}</style><rect width="720" height="550" fill="white"/>'+els.board.innerHTML+'</svg>');els.back.onclick();assert.equal(get('lab.updates'),0);assert.equal(get('lab.s'),0);assert.equal(get('lab.q[0][0]'),0);els.living.value='0';assert.ok(!html.includes('id="noise"'));
// Train, then export SVG for visual inspection with an SVG renderer.
await els.train.onclick();assert.equal(get('lab.completed+lab.truncated'),100);assert.equal(els.next.disabled,false);els.policy.checked=true;els.policy.onchange();
if(process.env.SVG_PREVIEW)fs.writeFileSync(process.env.SVG_PREVIEW,'<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="764" viewBox="0 0 720 550">'+els.board.innerHTML+'</svg>');
els.csv.onclick();assert.equal(exportCount,1);els.learning.checked=false;const q=get('JSON.stringify(lab.q)');els.next.onclick();els.next.onclick();els.next.onclick();assert.equal(get('JSON.stringify(lab.q)'),q);// Check independent tab progress, deterministic cliff transitions and rewards.
const oldGrid=get('JSON.stringify(lab.q)');els['tab-cliff'].onclick();assert.equal(get('lab.map.width'),7);assert.equal(get('lab.s'),8);assert.ok(els.board.innerHTML.includes('−100 OCEAN'));assert.ok(els.board.innerHTML.includes('+10 ISLAND'));els.east.onclick();assert.equal(get('lab.s'),9);assert.equal(get('lab.updates'),1);els['tab-grid'].onclick();assert.equal(get('JSON.stringify(lab.q)'),oldGrid);els['tab-cliff'].onclick();assert.equal(get('lab.s'),9);els.back.onclick();assert.equal(get('lab.s'),8);
if(process.env.SVG_PREVIEW)fs.writeFileSync(process.env.SVG_PREVIEW+'.cliff.svg','<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="657" viewBox="0 0 1206 550"><style>text{font-family:Arial,sans-serif}</style><rect width="1206" height="550" fill="white"/>'+els.board.innerHTML+'</svg>');
els.north.onclick();assert.equal(get('lab.s'),15);els.exit.onclick();assert.equal(get('lab.last.reward'),-100);assert.equal(get('lab.q[15][4]'),-50);els.reset.onclick();assert.equal(get('lab.updates'),0);console.log('PASS control logic: immediate update, deterministic manual buttons, undo, training, frozen moves, export and reset.');})().catch(e=>{console.error(e);process.exitCode=1});
