const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=path.join(__dirname,'..'),els={};
function element(){return {value:'',checked:false,disabled:false,hidden:false,textContent:'',_html:'',set innerHTML(s){this._html=s;parse(s)},get innerHTML(){return this._html},setAttribute(k,v){this[k]=v},after(){},append(){},click(){if(!this.disabled)return this.onclick?.()}};}
function parse(s){for(const m of s.matchAll(/<[^>]+\bid="([^"]+)"[^>]*>/g)){const e=els[m[1]] ||=element();e.value=m[0].match(/value="([^"]*)"/)?.[1]||e.value;e.checked=m[0].includes(' checked');}}
parse(fs.readFileSync(path.join(base,'src/template.html'),'utf8'));
const ctx={console,setTimeout,clearTimeout,GridLab:require('../src/engine'),PacmanLab:require('../src/pacman-engine'),confirm:()=>true,document:{getElementById(id){if(id==='tab-pac'&&!els[id])els[id]=tab;assert.ok(els[id],id);return els[id]},createElement(){const e=element();created.push(e);return e},querySelector(){return element()},addEventListener(){}}};const created=[];let tab;
const OriginalPac=ctx.PacmanLab.PacLab;let current;ctx.PacmanLab={...ctx.PacmanLab,PacLab:class extends OriginalPac{constructor(...args){super(...args);current=this;}}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(base,'src/app.js'),'utf8'),ctx);
// New tab is created after panel markup; record creation for lookup.
ctx.document.createElement=()=>{const e=element();if(created.length===1)tab=e;created.push(e);return e};
vm.runInContext(fs.readFileSync(path.join(base,'src/pacman.js'),'utf8'),ctx);
(async()=>{tab.click();assert.equal(els.layout.hidden,true);els['pac-step'].click();assert.match(els['pac-q-0'].innerHTML,/Updated immediately/);await els['pac-train'].click();assert.match(els['pac-progress'].textContent,/100 episodes/);const learned=JSON.stringify(current.q),position=current.pos,episode=current.episode;els['pac-eps-0'].value='0.05';els['pac-eps-0'].oninput();assert.equal(JSON.stringify(current.q),learned);assert.equal(current.pos,position);assert.equal(current.episode,episode);assert.equal(els['pac-eps-1'],undefined);els['pac-eval'].checked=true;els['pac-eval'].onchange();els['pac-step'].click();els['pac-step'].click();assert.match(els['pac-q-0'].innerHTML,/frozen/);els['tab-grid'].click();assert.equal(els.layout.hidden,false);assert.equal(els['tab-grid']['aria-selected'],'true');tab.click();els['pac-reset'].click();assert.match(els['pac-episode-0'].textContent,/Episode 1 · 0/);assert.equal(els['pac-eps-0'].value,'0.80');console.log('PASS Pac-Man integration: tabs, step, 100 episodes, greedy viewing, reset.');})().catch(e=>{console.error(e);process.exitCode=1});
